name: Test pylibczirw binary wheel install on macOS (ARM)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest  # This is an ARM runner (Apple Silicon)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          environment-name: eubizarr

      - name: Install dependencies in Conda env
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge openjdk=11.* maven

      - name: Install eubi-bridge (binary-only test)
        shell: bash -l {0}
        run: |
          pip install --only-binary=:all: --no-cache-dir eubi-bridge==0.0.7b4

