name: Test pylibczirw on macOS without cmake, zlib and boost

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          environment-name: eubizarr

      - name: Install dependencies in Conda env
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge openjdk=11.* maven

      - name: Install eubi-bridge via pip
        shell: bash -l {0}
        run: |
          pip install --no-cache-dir eubi-bridge==0.0.7b4
